[package]
name = "emma"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
fehler = "1.0"
thiserror = "1.0"

argh = "0.1"
crossbeam-channel = "0.5"
dirs = "3.0"
log = "0.4"
nix = "0.19"
rand = "0.8"
rusqlite = "0.24"
syntect = "4.5"

bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

gtk4 = { git = "https://github.com/gtk-rs/gtk4.git", rev = "70dbed1242a84f45b11fbc1a67cce4e22de331c6" }
