[package]
name = "emma"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
# Error handling
anyhow = "1.0.53"
fehler = "1.0.0"
fs-err = "2.6.0"
thiserror = "1.0.30"

# GUI
gtk4 = { git = "https://github.com/gtk-rs/gtk4.git" }
pangocairo = { git = "https://github.com/gtk-rs/gtk-rs-core" }

# Logging
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.6", default-features = false, features = ["env-filter", "fmt"] }

# Sync
parking_lot = "0.11.2"

# Text
aho-corasick = "0.7.18"
ropey = "1.3.2"
syntect = "4.6.0"
unicode-segmentation = "1.8.0"

# Other
dirs = "4.0.0"
rand = "0.8.4"
serde = { version = "1.0.135", features = ["derive"] }
serde_yaml = "0.8.23"

[dev-dependencies]
tempfile = "3.3.0"

[profile.dev.package."*"]
opt-level = 3
