[package]
name = "emma"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
fehler = "1.0"

crossbeam-channel = "0.5"

bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }

gdk = "0.13"
glib = "0.10"
gio = "0.9"
gtk = "0.9"
