[package]
name = "emma"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
fehler = "1.0"
fs-err = "2.5"
thiserror = "1.0"

log = "0.4"
env_logger = "0.8"

argh = "0.1"
crossbeam-channel = "0.5"
dirs = "3.0"
nix = "0.19"
rand = "0.8"
rusqlite = "0.24"

ropey = "1.2"
syntect = "4.5"

bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

gtk4 = { git = "https://github.com/gtk-rs/gtk4.git", rev = "3595eff1ddd3c2eb234b4c0181914c1c1d874a87" }
