[package]
name = "emma"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
fehler = "1.0"
thiserror = "1.0"

argh = "0.1"
crossbeam-channel = "0.5"
rand = "0.8"
syntect = "4.5"

bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

gdk = "0.13"
glib = "0.10"
gio = "0.9"
gtk = { version = "0.9", features = ["v3_16"] }
sourceview = "0.9"
