[package]
name = "emma"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1.1.0"
anyhow = "1.0.58"
dirs = "4.0.0"
fehler = "1.0.0"
fs-err = "3.0.0"
gtk4 = { git = "https://github.com/gtk-rs/gtk4.git" }
nix = "0.24.2"
once_cell = "1.13.0"
pangocairo = { git = "https://github.com/gtk-rs/gtk-rs-core" }
rand = "0.8.5"
ropey = "1.5.0"
rusqlite = { version = "0.28.0", features = ["bundled"] }
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
serde_yaml = "0.8.26"
syntect = "5.0.0"
thiserror = "1.0.31"
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", default-features = false, features = ["env-filter", "fmt"] }
unicode-segmentation = "1.9.0"

[dev-dependencies]
tempfile = "3.3.0"

[profile.dev.package."*"]
opt-level = 3
