[package]
name = "emma"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
fehler = "1.0"

bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }

gio = "0.9"
gtk = "0.9"
